# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 345b2b62888061caf936d75f7a9f34ab3dd765fcb0e23b0519b88b4b17843e269eba9a1cdf67d897cf1487adfc2187cd12b090eafdd037f362a1fb07556dbeb8

test:
  secret_key_base: 764ed824fc74472b992c72e6ca527273b005daa5703150fc535fb0c2c43aee027c03efdbf7dc3f5471a708b982b719d7bb71cc7c71419e38f8ed518e69b86f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
